name: "deeptools_bigwigcompare"
description: Compare two bigWig files based on the number of mapped reads
keywords:
  - bigwig
  - compare
  - genomics
  - deeptools
  - coverage
tools:
  - "deeptools":
      description: A set of user-friendly tools for normalization and
        visualization of deep-sequencing data
      homepage: https://deeptools.readthedocs.io/en/develop/
      documentation: https://deeptools.readthedocs.io/en/develop/content/tools/bigwigCompare.html
      tool_dev_url: https://github.com/deeptools/deepTools
      doi: "10.1093/nar/gku365"
      licence:
        - "GPL v3"
      identifier: "biotools:deeptools"
      args_id: "$args"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - bigwig1:
        type: file
        description: First bigWig file (usually treatment)
        pattern: "*.{bw,bigwig,bigWig}"
        ontologies:
          - edam: "http://edamontology.org/data_3002"
          - edam: "http://edamontology.org/format_3006"
    - bigwig2:
        type: file
        description: Second bigWig file (usually control)
        pattern: "*.{bw,bigwig,bigWig}"
        ontologies:
          - edam: "http://edamontology.org/data_3002"
          - edam: "http://edamontology.org/format_3006"
  - - meta2:
        type: map
        description: |
          Groovy Map containing blacklist metadata
          e.g. [ id:'blacklist' ]
    - blacklist:
        type: file
        description: BED/GTF file containing regions to exclude from analysis
        pattern: "*.{bed,gtf}"
        ontologies:
          - edam: "http://edamontology.org/data_3002"
          - edam: "http://edamontology.org/format_3003"
        optional: true
output:
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
      - "*.{bigWig,bedgraph}":
          type: file
          description: Output bigWig or bedGraph file with comparison results
          pattern: "*.{bigWig,bedgraph}"
          ontologies:
            - edam: "http://edamontology.org/format_3583"
            - edam: "http://edamontology.org/format_3006"
  versions_deeptools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - bigwigCompare --version | sed "s/bigwigCompare //g":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - bigwigCompare --version | sed "s/bigwigCompare //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nadiaxaidan"
  - "@daisymut"
  - "@ugoiannacchero"
maintainers:
  - "@nadiaxaidan"
  - "@daisymut"
  - "@ugoiannacchero"
