name: "custom_addmostsevereconsequence"
description: Annotate a VEP annotated VCF with the most severe consequence field
keywords:
  - annotation
  - vep
  - consequence
  - vcf
tools:
  - "custom":
      description: "Custom module to annotate a VEP annotated VCF with the most severe
        consequence field"
      tool_dev_url: "https://github.com/nf-core/modules/blob/master/modules/nf-core/custom/addmostsevereconsequence/main.nf"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - vcf:
        type: file
        description: VEP annotated VCF file
        pattern: "*.{vcf,vcf.gz}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - variant_consequences:
        type: file
        description: File with VEP variant consequences, one per line.
        pattern: "*"
        ontologies: []
output:
  vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.vcf.gz":
          type: file
          description: Annotated VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989
  versions_addmostsevereconsequence:
    - - ${task.process}:
          type: string
          description: The name of the process
      - addmostsevereconsequence:
          type: string
          description: The name of the tool
      - "1.1":
          type: string
          description: The expression to obtain the version of the tool
  versions_bgzip:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bgzip:
          type: string
          description: The name of the tool
      - bgzip --version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - addmostsevereconsequence:
          type: string
          description: The name of the tool
      - "1.1":
          type: string
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - bgzip:
          type: string
          description: The name of the tool
      - bgzip --version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@ramprasadn"
  - "@fellen31"
maintainers:
  - "@ramprasadn"
  - "@fellen31"
