name: deeptools_plotheatmap
description: plots values produced by deeptools_computematrix as a heatmap
keywords:
  - plot
  - heatmap
  - scores
  - matrix
tools:
  - deeptools:
      description: A set of user-friendly tools for normalization and
        visualization of deep-sequencing data
      documentation: https://deeptools.readthedocs.io/en/develop/index.html
      tool_dev_url: https://github.com/deeptools/deepTools
      doi: "10.1093/nar/gku365"
      licence:
        - "GPL v3"
      identifier: biotools:deeptools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - matrix:
        type: file
        description: |
          gzipped matrix file produced by deeptools_
          computematrix deeptools utility
        pattern: "*.{mat.gz}"
        ontologies: []
output:
  pdf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.pdf":
          type: file
          description: |
            Output figure containing resulting plot
          pattern: "*.{plotHeatmap.pdf}"
          ontologies: []
  table:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tab":
          type: file
          description: Output table
          ontologies: []
  versions_deeptools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - plotHeatmap --version | sed "s/plotHeatmap //g":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - plotHeatmap --version | sed "s/plotHeatmap //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@edmundmiller"
  - "@drpatelh"
  - "@joseespinosa"
maintainers:
  - "@edmundmiller"
  - "@drpatelh"
  - "@joseespinosa"
