name: "windowmasker_convert"
description: Masks out highly repetitive DNA sequences with low complexity in a genome
keywords:
  - fasta
  - blast
  - windowmasker
tools:
  - windowmasker:
      description: "A program to mask highly repetitive and low complexity DNA sequences
        within a genome."
      homepage: "https://blast.ncbi.nlm.nih.gov/Blast.cgi"
      documentation: "ftp://ftp.ncbi.nlm.nih.gov/pub/agarwala/windowmasker/README.windowmasker"
      doi: 10.1016/S0022-2836(05)80360-2
      licence: ["US-Government-Work"]
      identifier: biotools:windowmasker
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - counts:
        type: file
        description: valid unit counts file
        pattern: "*.{ascii,binary,oascii,obinary,txt}"
        ontologies: []
output:
  converted:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${output}:
          type: file
          description: converted file
          ontologies: []
  versions_windowmasker:
    - - ${task.process}:
          type: string
          description: The name of the process
      - windowmasker:
          type: string
          description: The name of the tool
      - windowmasker -version-full | head -n 1 | sed 's/^.*windowmasker. //; s/ .*\$//':
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - windowmasker:
          type: string
          description: The name of the tool
      - windowmasker -version-full | head -n 1 | sed 's/^.*windowmasker. //; s/ .*\$//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@alxndrdiaz"
maintainers:
  - "@alxndrdiaz"
