name: "meryl_histogram"
description: A genomic k-mer counter (and sequence utility) with nice features.
keywords:
  - k-mer
  - histogram
  - reference-free
tools:
  - "meryl":
      description: "A genomic k-mer counter (and sequence utility) with nice features. "
      homepage: "https://github.com/marbl/meryl"
      documentation: "https://meryl.readthedocs.io/en/latest/quick-start.html"
      tool_dev_url: "https://github.com/marbl/meryl"
      licence:
        - "GPL"
      identifier: biotools:meryl
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - meryl_db:
        type: directory
        description: Meryl k-mer database
  - kvalue:
      type: integer
      description: An integer value of k to use as the k-mer value.
output:
  hist:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.hist":
          type: file
          description: Histogram of k-mers
          pattern: "*.hist"
          ontologies: []
  versions_meryl:
    - - ${task.process}:
          type: string
          description: The name of the process
      - meryl:
          type: string
          description: The name of the tool
      - meryl --version |& sed 's/meryl //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - meryl:
          type: string
          description: The name of the tool
      - meryl --version |& sed 's/meryl //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@mahesh-panchal"
maintainers:
  - "@mahesh-panchal"
  - "@gallvp"
