name: "alignoth"
description: Creating alignment plots from bam files
keywords:
  - genomics
  - alignment
  - visualization
  - pileup
  - plotting
tools:
  - "alignoth":
      description: "A tool for creating alignment plots from bam files."
      homepage: "https://github.com/alignoth/alignoth/blob/v1.4.6/README.md"
      documentation: "https://github.com/alignoth/alignoth/blob/v1.4.6/README.md"
      tool_dev_url: "https://github.com/alignoth/alignoth"
      doi: "10.1093/bioinformatics/btaf663"
      licence:
        - "MIT"
      identifier: biotools:alignoth
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file to be visualized
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
    - bai:
        type: file
        description: Index file for the BAM/CRAM/SAM file
        pattern: "*.{bai,crai}"
        ontologies: []
    - fasta:
        type: file
        description: Reference fasta file
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: "http://edamontology.org/format_1929"
    - fai:
        type: file
        description: Index file for the reference fasta file
        pattern: "*.{fa,fasta}.fai"
        ontologies: []
    - bed:
        type: file
        description: Bed file with regions to be visualized (optional)
        pattern: "*.bed"
        ontologies:
          - edam: "http://edamontology.org/format_3003"
    - vcf:
        type: file
        description: VCF file with variants to be highlighted (optional)
        pattern: "*.vcf"
        ontologies:
          - edam: "http://edamontology.org/format_3016"
    - tbi:
        type: file
        description: Index file for the VCF file
        pattern: "*.vcf.tbi"
        ontologies: []
output:
  html:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}.html":
          type: file
          description: HTML file with the alignment plot
          pattern: "*.html"
          ontologies:
            - edam: "http://edamontology.org/format_2331"
  output:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}":
          type: directory
          description: Output directory with the alignment plot and all
            intermediate files
          pattern: "*"
  vl_json:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}.vl.json":
          type: file
          description: Vega-Lite JSON file with the alignment plot
          pattern: "*.vl.json"
          ontologies:
            - edam: "http://edamontology.org/format_3464"
  versions_alignoth:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "alignoth":
          type: string
          description: The name of the tool
      - "alignoth --version | sed 's/alignoth //g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "alignoth":
          type: string
          description: The name of the tool
      - "alignoth --version | sed 's/alignoth //g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@famosab"
maintainers:
  - "@famosab"
