name: "ngsbits_samplegender"
description: Determines the gender of a sample from the BAM/CRAM file.
keywords:
  - gender
  - cram
  - bam
  - short reads
tools:
  - "ngsbits":
      description: "Short-read sequencing tools"
      homepage: "https://github.com/imgag/ngs-bits"
      documentation: "https://github.com/imgag/ngs-bits"
      tool_dev_url: "https://github.com/imgag/ngs-bits"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - bam:
        type: file
        description: One or more BAM/CRAM files to determine the gender of
        pattern: "*.{bam,cram}"
        ontologies: []
    - bai:
        type: file
        description: The index file(s) from the input BAM/CRAM file(s)
        pattern: "*.{bai,crai}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference fasta information
          e.g. [ id:'test' ]
    - fasta:
        type: file
        description: The reference FASTA to use (mandatory when CRAM files are
          used)
        pattern: "*.{fasta,fa,fna}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing reference fasta information
          e.g. [ id:'test' ]
    - fai:
        type: file
        description: The index file from the reference FASTA
        pattern: "*.fai"
        ontologies: []
  - method:
      type: string
      description: The method to use to define the gender (possibilities are 'xy',
        'hetx' and 'sry')
      pattern: "(xy|hetx|sry)"
output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tsv":
          type: file
          description: An output TSV file containing the results of the gender
            prediction
          pattern: "*.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475
  versions_ngsbits:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngsbits:
          type: string
          description: The name of the tool
      - SampleGender --version  2>&1 | sed 's/SampleGender //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - ngsbits:
          type: string
          description: The name of the tool
      - SampleGender --version  2>&1 | sed 's/SampleGender //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
