name: "upp_align"
description: Aligns protein structures using UPP
keywords:
  - alignment
  - MSA
  - genomics
  - structure
tools:
  - "upp":
      description: "SATe-enabled phylogenetic placement"
      homepage: "https://github.com/smirarab/sepp/tree/master"
      documentation: "https://github.com/smirarab/sepp/blob/master/README.UPP.md"
      tool_dev_url: "https://github.com/smirarab/sepp/tree/master"
      doi: "10.1093/bioinformatics/btad007"
      licence:
        - "GPL v3"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test']`
    - fasta_unaligned:
        type: file
        description: Unaligned sequence file. If no backbone tree nor alignment is
          given, the sequence file will be randomly split into a backbone set and
          query set
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1919 # SEQUENCE-LIKE
          - edam: http://edamontology.org/format_1929 # FASTA
    - fasta_aligned:
        type: file
        description: Aligned sequence file. (optional)
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1919 # SEQUENCE-LIKE
          - edam: http://edamontology.org/format_1929 # FASTA
  - - meta2:
        type: map
        description: |
          Groovy Map containing tree information
          e.g. `[ id:'test_tree']`
    - tree:
        type: file
        description: Input guide tree in Newick format
        pattern: "*.{dnd}"
        ontologies:
          - edam: http://edamontology.org/format_2006
  - compress:
      type: boolean
      description: Flag representing whether the output MSA should be compressed.
        Set to true to enable/false to disable compression.
output:
  alignment:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test']`
      - "*.aln{.gz,}":
          type: file
          description: Alignment file, in FASTA format. May be gzipped or
            uncompressed, depending on if compress is set to true or false
          pattern: "*.aln{.gz,}"
          ontologies:
            - edam: http://edamontology.org/format_2554
            - edam: http://edamontology.org/format_1921
            - edam: http://edamontology.org/format_1984
  versions_upp:
    - - ${task.process}:
          type: string
          description: The name of the process
      - upp:
          type: string
          description: The name of the tool
      - run_upp.py -v | grep "run_upp" | cut -f2 -d" ":
          type: eval
          description: The expression to obtain the version of the tool
  versions_pigz:
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed "s/^.*pigz[[:space:]]*//":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - upp:
          type: string
          description: The name of the tool
      - run_upp.py -v | grep "run_upp" | cut -f2 -d" ":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1 | sed "s/^.*pigz[[:space:]]*//":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@luisas"
maintainers:
  - "@luisas"
