name: peddy
description: Manipulation, validation and exploration of pedigrees
keywords:
  - pedigrees
  - ped
  - family
tools:
  - peddy:
      description: genotype, ped correspondence check, ancestry check, sex check.
        directly, quickly on VCF
      homepage: https://github.com/brentp/peddy
      documentation: https://peddy.readthedocs.io/en/latest/
      tool_dev_url: https://github.com/brentp/peddy
      doi: "10.1016/j.ajhg.2017.01.017"
      licence:
        - "MIT"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: VCF file
        pattern: "*.vcf.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989
    - vcf_tbi:
        type: file
        description: TBI file
        pattern: "*.vcf.gz.tbi"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - ped:
        type: file
        description: PED/FAM file
        pattern: "*.{ped,fam}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - sites:
        type: file
        description: sites file. By defaults peddy uses hg19/GRCh37, "--sites
          hg38" can be specified in the process argument or a custom file
          following syntax
          https://github.com/brentp/peddy/blob/master/peddy/GRCH37.sites can be
          provided
        pattern: "*.sites"
        ontologies: []
output:
  vs_html:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.vs.html:
          type: file
          description: HTML file comparison between reported and inferred sex
          pattern: "*.vs.html"
          ontologies: []
  html:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.html:
          type: file
          description: HTML report
          pattern: "*.html"
          ontologies: []
  ped:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.peddy.ped:
          type: file
          description: Inferred PED file
          pattern: "*.peddy.ped"
          ontologies: []
  het_check_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.het_check.png:
          type: file
          description: |
            PNG file containing heterozygosity check.
            Rate of het calls, allele-balance at het calls,
            mean and median depth, and a PCA projection onto thousand
            genomes.
          pattern: "*.het_check.png"
          ontologies: []
  ped_check_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.ped_check.png:
          type: file
          description: |
            PNG file containing pedigree check between reported
            and inferred  sex
          pattern: "*.het_check.png"
          ontologies: []
  sex_check_png:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.sex_check.png:
          type: file
          description: |
            PNG file with sex check performs a comparison
            between the sex reported in the ped file and that
            inferred from the genotypes on the non-PAR regions
            of the X chromosome.
          pattern: "*.sex_check.png"
          ontologies: []
  het_check_csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.het_check.csv:
          type: file
          description: |
            CSV file containing heterozygosity check.
            Rate of het calls, allele-balance at het calls,
            mean and median depth, and a PCA projection onto thousand
            genomes.
          pattern: "*.het_check.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
  ped_check_csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.ped_check.csv:
          type: file
          description: |
            CSV file containing pedigree check between reported
            and inferred  sex
          pattern: "*.het_check.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
  sex_check_csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.sex_check.csv:
          type: file
          description: |
            CSV file with sex check performs a comparison
            between the sex reported in the ped file and that
            inferred from the genotypes on the non-PAR regions
            of the X chromosome.
          pattern: "*.sex_check.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
  ped_check_rel_difference_csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - ${prefix}.ped_check.rel-difference.csv:
          type: file
          description: |
            CSV file with the comparison between inferred and given relatedness
          pattern: "*.ped_check.rel-difference.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752
  versions_peddy:
    - - ${task.process}:
          type: string
          description: The name of the process
      - peddy:
          type: string
          description: The name of the tool
      - peddy --version | sed 's/peddy, version //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - peddy:
          type: string
          description: The name of the tool
      - peddy --version | sed 's/peddy, version //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@rannick"
maintainers:
  - "@rannick"
