name: "happy_prepy"
description: Pre.py is a preprocessing tool made to preprocess VCF files for Hap.py
keywords:
  - happy
  - benchmark
  - haplotype
tools:
  - "happy":
      description: Haplotype VCF comparison tools
      homepage: https://www.illumina.com/products/by-type/informatics-products/basespace-sequence-hub/apps/hap-py-benchmarking.html
      documentation: https://github.com/Illumina/hap.py
      tool_dev_url: https://github.com/Illumina/hap.py
      licence: ["BSD-2-clause"]
      identifier: biotools:happy
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: VCF file to preprocess
        pattern: "*.{vcf,vcf.gz}"
        ontologies: []
    - bed:
        type: file
        description: BED file
        pattern: "*.bed"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information for reference fasta
          e.g. [ id:'test2']
    - fasta:
        type: file
        description: FASTA file of the reference genome
        pattern: "*.{fa,fasta}"
        ontologies: []
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information for reference fai
          e.g. [ id:'test3' ]
    - fasta_fai:
        type: file
        description: The index of the reference FASTA
        pattern: "*.fai"
        ontologies: []
output:
  preprocessed_vcf:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.vcf.gz":
          type: file
          description: Preprocessed VCF file
          pattern: "*.vcf.gz"
          ontologies:
            - edam: http://edamontology.org/format_3989 # GZIP format
  versions_happy:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - happy:
          type: string
          description: The tool name
      - "0.3.15":
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - happy:
          type: string
          description: The tool name
      - "0.3.15":
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
