name: "bedops_gtf2bed"
description: Convert gtf format to bed format
keywords:
  - gtf
  - bed
  - conversion
tools:
  - gtf2bed:
      description: The gtf2bed script converts 1-based, closed [start, end] Gene
        Transfer Format v2.2 (GTF2.2) to sorted, 0-based, half-open [start-1, end)
        extended BED-formatted data.
      homepage: https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/gtf2bed.html
      documentation: https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/gtf2bed.html
      tool_dev_url: https://github.com/bedops/bedops
      doi: 10.1093/bioinformatics/bts277
      licence:
        - "GPL v2"
      identifier: biotools:bedops
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - gtf:
        type: file
        description: A reference file in GTF format
        pattern: "*.{gtf,gtf.gz}"
        ontologies: []
output:
  bed:
    - - meta:
          type: file
          description: A reference file in BED format
          pattern: "*.{bed}"
          ontologies: []
      - "*.bed":
          type: file
          description: A reference file in BED format
          pattern: "*.{bed}"
          ontologies: []
  versions_bedops:
    - - ${task.process}:
          type: string
          description: "The name of the process"
      - bedops:
          type: string
          description: The name of the tool
      - 'bedops --version | sed -n "s/.*version: *\([^ ]*\).*/\1/p"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: "The name of the process"
      - bedops:
          type: string
          description: The name of the tool
      - 'bedops --version | sed -n "s/.*version: *\([^ ]*\).*/\1/p"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@davidecarlson"
