name: "bedops_convert2bed"
description: Convert BAM/GFF/GTF/GVF/PSL files to bed
keywords:
  - convert
  - bed
  - genomics
tools:
  - "bedops":
      description: "High-performance genomic feature operations."
      homepage: "https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/convert2bed.html#convert2bed"
      documentation: "https://bedops.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/bedops"
      doi: "10.1093/bioinformatics/bts277"
      licence:
        - "GNU v2"
      identifier: biotools:bedops
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - in_file:
        type: file
        description: Input file
        ontologies: []
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.bed":
          type: file
          description: Sorted BED file
          pattern: "*.{bed}"
          ontologies: []
  versions_bedops:
    - - ${task.process}:
          type: string
          description: "The name of the process"
      - bedops:
          type: string
          description: The name of the tool
      - 'convert2bed --version | sed -n "s/.*version: *\([^ ]*\).*/\1/p"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: "The name of the process"
      - bedops:
          type: string
          description: The name of the tool
      - 'convert2bed --version | sed -n "s/.*version: *\([^ ]*\).*/\1/p"':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@rannick"
maintainers:
  - "@rannick"
