name: deeptools_computematrix
description: calculates scores per genome regions for other deeptools plotting
  utilities
keywords:
  - genome
  - regions
  - scores
  - matrix
tools:
  - deeptools:
      description: A set of user-friendly tools for normalization and
        visualization of deep-sequencing data
      documentation: https://deeptools.readthedocs.io/en/develop/index.html
      tool_dev_url: https://github.com/deeptools/deepTools
      doi: "10.1093/nar/gku365"
      licence:
        - "GPL v3"
      identifier: biotools:deeptools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test' ]
    - bigwig:
        type: file
        description: bigwig file containing genomic scores
        pattern: "*.{bw,bigwig}"
        ontologies: []
  - bed:
      type: file
      description: bed file containing genomic regions
      pattern: "*.{bed}"
      ontologies: []
output:
  matrix:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.mat.gz":
          type: file
          description: |
            gzipped matrix file needed by the plotHeatmap and plotProfile
            deeptools utilities
          pattern: "*.{computeMatrix.mat.gz}"
          ontologies: []
  table:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.mat.tab":
          type: file
          description: |
            tabular file containing the scores of the generated matrix
          pattern: "*.{computeMatrix.vals.mat.tab}"
          ontologies: []
  versions_deeptools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - computeMatrix --version | sed "s/computeMatrix //g":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - computeMatrix --version | sed "s/computeMatrix //g":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@jeremy1805"
  - "@edmundmiller"
  - "@drpatelh"
  - "@joseespinosa"
maintainers:
  - "@jeremy1805"
  - "@edmundmiller"
  - "@drpatelh"
  - "@joseespinosa"
