name: deeptools_alignmentSieve
description: This tool filters alignments in a BAM/CRAM file according the the
  specified parameters.
keywords:
  - ATACseq
  - filter
  - shift
  - ATACshift
tools:
  - deeptools:
      description: A set of user-friendly tools for normalization and
        visualization of deep-sequencing data
      homepage: https://deeptools.readthedocs.io/en/develop/content/tools/alignmentSieve.html
      documentation: https://deeptools.readthedocs.io/en/develop/content/tools/alignmentSieve.html
      tool_dev_url: https://github.com/deeptools/deepTools/
      doi: "10.1093/nar/gkw257"
      licence:
        - "GPL v3"
      identifier: biotools:deeptools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: BAM file
        pattern: "*.{bam}"
        ontologies: []
    - input_index:
        type: file
        description: BAM index file
        pattern: "*.{bai}"
        ontologies: []
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_as.bam":
          type: file
          description: BAM file
          pattern: "*.bam"
          ontologies: []
  logs:
    - "*_log.txt":
        type: file
        description: TXT file
        pattern: "*.txt"
        ontologies: []
  versions_deeptools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - alignmentSieve --version | sed "s/alignmentSieve //g":
          type: eval
          description: The expression to obtain the version of the tool
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - deeptools:
          type: string
          description: The name of the tool
      - alignmentSieve --version | sed "s/alignmentSieve //g":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@lpantano"
maintainers:
  - "@lpantano"
