name: "svtk_vcf2bed"
description: Converts VCFs containing structural variants to BED format
keywords:
  - vcf
  - bed
  - vcf2bed
  - svtk
  - structural variants
tools:
  - "svtk":
      description: "Utilities for consolidating, filtering, resolving, and annotating
        structural variants."
      homepage: "https://github.com/broadinstitute/gatk-sv/tree/master/src/svtk"
      documentation: "https://github.com/broadinstitute/gatk-sv/tree/master/src/svtk"
      tool_dev_url: "https://github.com/broadinstitute/gatk-sv/tree/master/src/svtk"
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - vcf:
        type: file
        description: A VCF file created with a structural variant caller
        pattern: "*.vcf.gz"
        ontologies:
          - edam: http://edamontology.org/format_3989 # GZIP format
    - tbi:
        type: file
        description: The index for the VCF file
        pattern: "*.vcf.gz.tbi"
        ontologies: []
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.bed":
          type: file
          description: The created BED file
          pattern: "*.bed"
          ontologies: []
  versions_svtk:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - svtk:
          type: string
          description: The tool name
      - "0.0.20190615":
          type: string
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - svtk:
          type: string
          description: The tool name
      - "0.0.20190615":
          type: string
          description: The expression to obtain the version of the tool
authors:
  - "@nvnieuwk"
maintainers:
  - "@nvnieuwk"
